// Generated by LiveScript 1.3.1
new ldText({
  root: 'h1',
  animations: [
    {
      className: "ld ld-bounce-in",
      duration: 1
    }, {
      className: "ld ld-bounce",
      delay: 0.3
    }
  ],
  colors: ['#51cacc', '#9df871', '#e0ff77', '#de9dd6', '#ff708e']
});
new ldText({
  root: '.p1',
  animations: [
    {
      className: "ld ld-float-btt-in"
    }, {
      className: "ld ld-metronome"
    }
  ]
});
new ldText({
  byWord: true,
  root: '.p2',
  animations: [{
    className: "ld ld-float-btt-in"
  }]
});