// Generated by LiveScript 1.3.1
(function(){
  var ldText;
  ldText = function(opt){
    opt == null && (opt = {});
    this.opt = opt;
    this.root = !opt.root
      ? document.createElement("div")
      : typeof opt.root === 'string'
        ? document.querySelector(opt.root)
        : opt.root;
    this.root.classList.add('ldtxt');
    this.setText(this.opt.text || this.root.textContent);
    this.animations = opt.animations || [];
    this.colors = opt.colors || null;
    this.prepare();
    return this;
  };
  ldText.prototype = import$(Object.create(Object.prototype), {
    setText: function(it){
      return this.text = it || " ... oi.loading.io ...";
    },
    prepare: function(){
      var nodes, c, i$, to$, i, idx, a, cls, ani;
      nodes = [];
      c = this.colors;
      for (i$ = 0, to$ = this.text.length; i$ < to$; ++i$) {
        i = i$;
        nodes.push("<span" + (c ? ' style="color:' + c[i % c.length] + '"' : '') + ">" + this.text[i] + "</span>");
      }
      for (i$ = 0, to$ = this.animations.length; i$ < to$; ++i$) {
        idx = i$;
        a = this.animations[idx];
        cls = a.className;
        ani = a.animation;
        nodes = nodes.map(fn$);
      }
      return this.root.innerHTML = nodes.join('');
      function fn$(d, i){
        var delay;
        delay = (a.latency || 1) * i / nodes.length;
        return "<span class=\"" + cls + "\" style=\"\n" + (ani ? 'animation:' + ani + ';' : '') + "animation-delay:" + delay + "s\">" + d + "</span>";
      }
    }
  });
  if (typeof module != 'undefined' && module !== null) {
    module.exports = ldText;
  }
  if (window) {
    return window.ldText = ldText;
  }
})();
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}